FROM nginx:latest

COPY dist/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# docker build -t web .
#  docker run -d --name zhenggong-web -p 80:80 web:latest